version: '2.1'
services:

  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: books
    healthcheck:
      test: "exit 0"

  springboot:
    build: .
    image: alvarofernandezavalos/springboot
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/books?verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysql
