spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 1234