name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: hanzou89
  IMAGE_NAME: springboot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run MySQL for unit testing
        run: cd dev && docker-compose up -d

      - name: Run the Maven verify goal
        run: mvn --batch-mode --update-snapshots verify

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags:  |
            - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.getVersion.outputs.version }}